const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.gamepad,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.progressbar,
		C3.Behaviors.TileMovement,
		C3.Behaviors.scrollto,
		C3.Plugins.Camera3D,
		C3.Plugins.Browser,
		C3.Behaviors.solid,
		C3.Plugins.iframe,
		C3.Plugins.HTMLElement,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.ScriptsInEvents.Startscreenevents_Event10,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.ScriptsInEvents.GameEvents_Event11,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.progressbar.Acts.SetCSSStyle,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.System.Acts.Wait,
		C3.ScriptsInEvents.AboutScreenEvents_Event6,
		C3.ScriptsInEvents.RedhouseEvents_Event6,
		C3.ScriptsInEvents.Game2Events_Event11,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.ScriptsInEvents.YellowHouseEvents_Event6,
		C3.ScriptsInEvents.PinkHouseEvents_Event6,
		C3.ScriptsInEvents.OrangeHouseEvents_Event6,
		C3.ScriptsInEvents.PurpleHouseEvents_Event6,
		C3.ScriptsInEvents.MintHouseEvents_Event6,
		C3.ScriptsInEvents.Game3Events_Event5
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{Gamepad: 0},
	{StartScreen: 0},
	{TitleText: 0},
	{PlayButtonFront: 0},
	{PlayButtonBack: 0},
	{PLayText: 0},
	{rclogo: 0},
	{pgbgameslogo: 0},
	{pgbgamestext: 0},
	{rctext: 0},
	{ProgressBar: 0},
	{aboutbutton: 0},
	{Instructions: 0},
	{NAME_FOR_ABOUT: 0},
	{aboutbacktomain: 0},
	{TileMovement: 0},
	{ScrollTo: 0},
	{player: 0},
	{LeftTouch: 0},
	{RightTouch: 0},
	{downtouch: 0},
	{uptouch: 0},
	{RedHouse: 0},
	{RedHouse_WhiteFrame: 0},
	{PinkBoxFrame: 0},
	{Question_RedHouse: 0},
	{Answer_RedHouse: 0},
	{NPC_RedHouse: 0},
	{NPCGreenShirtBluePants: 0},
	{mousegif: 0},
	{Browser: 0},
	{YellowHouse: 0},
	{PinkHouse: 0},
	{Solid: 0},
	{Sprite2: 0},
	{moreArrow: 0},
	{more: 0},
	{Sprite3: 0},
	{YellowQuestion: 0},
	{YellowAnswer: 0},
	{PinkHouseNPC: 0},
	{WhatIsAChippertextOnlyAttackQuestion: 0},
	{ChippertextOnlyAttackExplaination: 0},
	{BackToGameScreen: 0},
	{PaleGreenHouse: 0},
	{PurpleHouse: 0},
	{PaleOrangeHouse: 0},
	{OrangeBoxFrame: 0},
	{GreenWavingNPC: 0},
	{PurpleBoxFrame: 0},
	{Sprite: 0},
	{MintBoxFrame: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{WhatIsAManInTheMiddleAttackQuestion: 0},
	{ManInTheMiddleAttackExplaination: 0},
	{WhatIsASideChannelAttackQuestion: 0},
	{SideChannelAttackExplaination: 0},
	{Text: 0},
	{Text2: 0},
	{YellowBoxFrame: 0},
	{RedBoxFrame: 0},
	{GoToGame3Bar: 0},
	{iframe: 0},
	{HTMLElement: 0},
	{Sprite6: 0},
	{HTMLElement2: 0},
	{iframe2: 0},
	{iframe3: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	StartScreen: class extends self.ISpriteInstance {},
	TitleText: class extends self.ITextInstance {},
	PlayButtonFront: class extends self.ISpriteInstance {},
	PlayButtonBack: class extends self.ISpriteInstance {},
	PLayText: class extends self.ITextInstance {},
	rclogo: class extends self.ISpriteInstance {},
	pgbgameslogo: class extends self.ISpriteInstance {},
	pgbgamestext: class extends self.ITextInstance {},
	rctext: class extends self.ITextInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	aboutbutton: class extends self.ISpriteInstance {},
	Instructions: class extends self.ITextInstance {},
	NAME_FOR_ABOUT: class extends self.ITextInstance {},
	aboutbacktomain: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	LeftTouch: class extends self.ISpriteInstance {},
	RightTouch: class extends self.ISpriteInstance {},
	downtouch: class extends self.ISpriteInstance {},
	uptouch: class extends self.ISpriteInstance {},
	RedHouse: class extends self.ISpriteInstance {},
	RedHouse_WhiteFrame: class extends self.IInstance {},
	PinkBoxFrame: class extends self.ISpriteInstance {},
	Question_RedHouse: class extends self.ITextInstance {},
	Answer_RedHouse: class extends self.ITextInstance {},
	NPC_RedHouse: class extends self.ISpriteInstance {},
	NPCGreenShirtBluePants: class extends self.ISpriteInstance {},
	mousegif: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	YellowHouse: class extends self.ISpriteInstance {},
	PinkHouse: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	moreArrow: class extends self.ISpriteInstance {},
	more: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	YellowQuestion: class extends self.ITextInstance {},
	YellowAnswer: class extends self.ITextInstance {},
	PinkHouseNPC: class extends self.ISpriteInstance {},
	WhatIsAChippertextOnlyAttackQuestion: class extends self.ITextInstance {},
	ChippertextOnlyAttackExplaination: class extends self.ITextInstance {},
	BackToGameScreen: class extends self.ITextInstance {},
	PaleGreenHouse: class extends self.ISpriteInstance {},
	PurpleHouse: class extends self.ISpriteInstance {},
	PaleOrangeHouse: class extends self.ISpriteInstance {},
	OrangeBoxFrame: class extends self.ISpriteInstance {},
	GreenWavingNPC: class extends self.ISpriteInstance {},
	PurpleBoxFrame: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	MintBoxFrame: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	WhatIsAManInTheMiddleAttackQuestion: class extends self.ITextInstance {},
	ManInTheMiddleAttackExplaination: class extends self.ITextInstance {},
	WhatIsASideChannelAttackQuestion: class extends self.ITextInstance {},
	SideChannelAttackExplaination: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	YellowBoxFrame: class extends self.ISpriteInstance {},
	RedBoxFrame: class extends self.ISpriteInstance {},
	GoToGame3Bar: class extends self.ISpriteInstance {},
	iframe: class extends self.IIframeInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	HTMLElement2: class extends self.IHTMLElementInstance {},
	iframe2: class extends self.IIframeInstance {},
	iframe3: class extends self.IIframeInstance {}
}